version: '3.8'

services:

  db:
    container_name: postgresql_db
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - db
    env_file:
      - ./.env

  test_db:
    container_name: test_postgresql_db
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "6000:5432"
    volumes:
      - test_database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: backend
    image: kaschenko/courier_service:v1
    restart: always
    depends_on:
      - db
      - test_db
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:1.21.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  database:
  test_database: