name: courie_service_workflow

on:
  push:
    branches: [ main ]

jobs:

  tests:
    runs-on: ubuntu-latest

    services:
          postgres:
            image: postgres:latest
            env:
              POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
              POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
              TZ: ${{ secrets.TIMEZONE }}
            ports:
              - 5432:5432
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        cd courier_service/
        pip install --no-cache-dir -r requirements.txt
    - name: Test with flake8
      run: |
        python -m flake8 courier_service/src/
        python -m flake8 courier_service/tests/
    - name: Run Pytest
      run: |
        pytest -v courier_service/tests/
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        DB_HOST_TEST: ${{ secrets.DB_HOST_TEST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        TIMEZONE: ${{ secrets.TIMEZONE }}
